begin;

-- Provide efficient, case-insensitive partial-name searching.
create extension if not exists pg_trgm with schema extensions;

set local search_path = public, extensions;

create index if not exists visitor_profiles_full_name_trgm_idx
  on public.visitor_profiles
  using gin (lower(full_name) gin_trgm_ops);

-- Stores only keyed request identifiers generated by the server.
-- Raw IP addresses must not be stored in this table.
create table if not exists public.public_request_limits (
  request_key text primary key,
  window_started_at timestamp with time zone not null default now(),
  request_count integer not null default 1,
  updated_at timestamp with time zone not null default now(),

  constraint public_request_limits_key_check
    check (
      char_length(request_key) >= 16
      and char_length(request_key) <= 200
    ),

  constraint public_request_limits_count_check
    check (request_count >= 1)
);

alter table public.public_request_limits enable row level security;

revoke all
  on table public.public_request_limits
  from public, anon, authenticated;

-- Atomically applies a fixed-window request limit.
-- The API will send an HMAC-derived key instead of a raw IP address.
create or replace function public.consume_public_rate_limit(
  p_request_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
volatile
set search_path = ''
as $function$
declare
  v_now timestamp with time zone := now();
  v_window interval;
  v_allowed boolean;
begin
  if p_request_key is null
    or char_length(p_request_key) < 16
    or char_length(p_request_key) > 200
  then
    return false;
  end if;

  if p_limit < 1 or p_limit > 1000 then
    return false;
  end if;

  if p_window_seconds < 60 or p_window_seconds > 86400 then
    return false;
  end if;

  v_window := make_interval(secs => p_window_seconds);

  insert into public.public_request_limits as limits (
    request_key,
    window_started_at,
    request_count,
    updated_at
  )
  values (
    p_request_key,
    v_now,
    1,
    v_now
  )
  on conflict (request_key)
  do update
  set
    request_count = case
      when limits.window_started_at <= v_now - v_window then 1
      else limits.request_count + 1
    end,
    window_started_at = case
      when limits.window_started_at <= v_now - v_window then v_now
      else limits.window_started_at
    end,
    updated_at = v_now
  returning request_count <= p_limit
  into v_allowed;

  return coalesce(v_allowed, false);
end;
$function$;

-- Returns a small result set to the trusted server.
-- The Vercel Function will mask these values before responding.
create or replace function public.search_returning_visitors(
  p_query text,
  p_limit integer default 7
)
returns table (
  visitor_id uuid,
  full_name text,
  organization text,
  phone_suffix text
)
language plpgsql
security definer
stable
set search_path = ''
as $function$
declare
  v_query text;
  v_pattern text;
  v_limit integer;
begin
  v_query := lower(
    regexp_replace(
      btrim(coalesce(p_query, '')),
      '[[:space:]]+',
      ' ',
      'g'
    )
  );

  if char_length(v_query) < 3 or char_length(v_query) > 80 then
    return;
  end if;

  v_limit := least(greatest(coalesce(p_limit, 7), 1), 7);

  -- Escape LIKE wildcards supplied as user input.
  v_pattern := replace(v_query, '\', '\\');
  v_pattern := replace(v_pattern, '%', '\%');
  v_pattern := replace(v_pattern, '_', '\_');

  return query
  select
    profile.id,
    profile.full_name,
    profile.organization,
    right(
      regexp_replace(profile.phone, '[^0-9]', '', 'g'),
      2
    )
  from public.visitor_profiles as profile
  where lower(profile.full_name)
    like '%' || v_pattern || '%' escape '\'
  order by
    case
      when lower(profile.full_name) = v_query then 0
      when lower(profile.full_name)
        like v_pattern || '%' escape '\' then 1
      else 2
    end,
    profile.full_name,
    profile.id
  limit v_limit;
end;
$function$;

-- Verifies the complete normalized telephone number.
-- No row is returned when either value does not match.
create or replace function public.verify_returning_visitor(
  p_visitor_id uuid,
  p_phone text
)
returns table (
  visitor_id uuid,
  full_name text,
  email text,
  organization text
)
language sql
security definer
stable
set search_path = ''
as $function$
  select
    profile.id,
    profile.full_name,
    profile.email,
    profile.organization
  from public.visitor_profiles as profile
  where profile.id = p_visitor_id
    and profile.phone = p_phone
  limit 1;
$function$;

-- PostgreSQL grants function execution to PUBLIC by default.
-- These functions must be accessible only through the trusted server client.
revoke execute
  on function public.consume_public_rate_limit(text, integer, integer)
  from public, anon, authenticated;

revoke execute
  on function public.search_returning_visitors(text, integer)
  from public, anon, authenticated;

revoke execute
  on function public.verify_returning_visitor(uuid, text)
  from public, anon, authenticated;

grant execute
  on function public.consume_public_rate_limit(text, integer, integer)
  to service_role;

grant execute
  on function public.search_returning_visitors(text, integer)
  to service_role;

grant execute
  on function public.verify_returning_visitor(uuid, text)
  to service_role;

notify pgrst, 'reload schema';

commit;